// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const_serializer.java
// Do not modify

package org.projectfloodlight.openflow.protocol.ver13;

import org.projectfloodlight.openflow.protocol.*;
import org.projectfloodlight.openflow.protocol.action.*;
import org.projectfloodlight.openflow.protocol.actionid.*;
import org.projectfloodlight.openflow.protocol.bsntlv.*;
import org.projectfloodlight.openflow.protocol.errormsg.*;
import org.projectfloodlight.openflow.protocol.meterband.*;
import org.projectfloodlight.openflow.protocol.instruction.*;
import org.projectfloodlight.openflow.protocol.instructionid.*;
import org.projectfloodlight.openflow.protocol.match.*;
import org.projectfloodlight.openflow.protocol.stat.*;
import org.projectfloodlight.openflow.protocol.oxm.*;
import org.projectfloodlight.openflow.protocol.oxs.*;
import org.projectfloodlight.openflow.protocol.queueprop.*;
import org.projectfloodlight.openflow.types.*;
import org.projectfloodlight.openflow.util.*;
import org.projectfloodlight.openflow.exceptions.*;
import org.projectfloodlight.openflow.protocol.OFPortOpticalTransportLayerClass;
import io.netty.buffer.ByteBuf;
import com.google.common.hash.PrimitiveSink;

public class OFPortOpticalTransportLayerClassSerializerVer13 {

    public final static byte PORT_VAL = (byte) 0x1;
    public final static byte OCH_VAL = (byte) 0x2;
    public final static byte ODU_VAL = (byte) 0x3;
    public final static byte ODUCLT_VAL = (byte) 0x4;

    public static OFPortOpticalTransportLayerClass readFrom(ByteBuf bb) throws OFParseError {
        try {
            return ofWireValue(bb.readByte());
        } catch (IllegalArgumentException e) {
            throw new OFParseError(e);
        }
    }

    public static void writeTo(ByteBuf bb, OFPortOpticalTransportLayerClass e) {
        bb.writeByte(toWireValue(e));
    }

    public static void putTo(OFPortOpticalTransportLayerClass e, PrimitiveSink sink) {
        sink.putByte(toWireValue(e));
    }

    public static OFPortOpticalTransportLayerClass ofWireValue(byte val) {
        switch(val) {
            case PORT_VAL:
                return OFPortOpticalTransportLayerClass.PORT;
            case OCH_VAL:
                return OFPortOpticalTransportLayerClass.OCH;
            case ODU_VAL:
                return OFPortOpticalTransportLayerClass.ODU;
            case ODUCLT_VAL:
                return OFPortOpticalTransportLayerClass.ODUCLT;
            default:
                throw new IllegalArgumentException("Illegal wire value for type OFPortOpticalTransportLayerClass in version 1.3: " + val);
        }
    }


    public static byte toWireValue(OFPortOpticalTransportLayerClass e) {
        switch(e) {
            case PORT:
                return PORT_VAL;
            case OCH:
                return OCH_VAL;
            case ODU:
                return ODU_VAL;
            case ODUCLT:
                return ODUCLT_VAL;
            default:
                throw new IllegalArgumentException("Illegal enum value for type OFPortOpticalTransportLayerClass in version 1.3: " + e);
        }
    }

}
